apiVersion: apps/v1
kind: Deployment 
metadata:
  name: my-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels : 
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:latest
        ports:
        - containerPort: 80 
---
  apiVersion: v1
  kind: Service 
  metadata:
    name: nginx-service
  spec:
    type: ClusterIP
    selector:
      app: my-app
    ports:
      - port: 80
        targetPort: 80
  


  

    

  
