apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: dev-team
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: dev-team
spec:
  selector:
    app: myapp
  type: LoadBalancer 
  ports:
  - name: nginx
    port: 80
    targetPort: 8080
