apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: devopsteam
  labels:
    name: my-nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      name: my-nginx
  template:
    metadata:
      labels:
        name: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        resources:
          requests:
            memory: "200Mi"
            cpu: "160m"
          limits:
            memory: "300Mi"
            cpu: "220m"
