apiVersion: v1
kind: ResourceQuota
metadata:
  name: resouces-rs-quota
  namespace: devopsteam
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
    